
kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git clone https://github.com/DangerousThings/smartcard-ci .
  - git submodule update --init --recursive
- name: build  
  image: plugins/docker
  settings:
    username: vivokeychristoph
    password:
      from_secret: docker_password
    repo: vivokey/smartcard-ci
    